### PR TITLE
Working on Design by Jason

### PR DESCRIPTION
**Pull request by shiffman**
@jasontheillustrator can you provide the character header as a transparent PNG and also any details about the font / line spacing settings you used? 

Current progress: https://deploy-preview-26--choochoo-whistle.netlify.app/

Whistle-Webpage-Mockup-1

### CODE REVIEW

**Comment by jasontheillustrator** [comment]
Here is the PNG header. 
Whistle-Webpage-Header

**Comment by jasontheillustrator** [comment]
Here's a breakdown for the design.
Screenshot 2023-01-16 at 8 46 48 AM

**Comment by jasontheillustrator** [comment]
For the font, if it's easier, you could probably just use the preexisting CSS to style the message.

**Comment by shiffman** [comment]
@jasontheillustrator can you add a header without the blue bar? That will likely be done as a CSS DIV and the hands will be transparent and overlay

**Comment by jasontheillustrator** [comment]
Here you go
Whistle-Webpage-Header-NoBar

**Comment by shiffman** [comment]
I was just thinking that a lot of people will pull up this page on their phone, should we design it more vertical or have it be responsive somehow? 

Screen Shot 2023-01-16 at 7 18 35 PM

**Comment by jasontheillustrator** [comment]
Yeah responsive would be good. would you want me to change the header graphic? i could just have 2 characters there and make them bigger so it's easier to see on mobile. 

As for the text, im assuming that would be something you would do on your end?

**Comment by jasontheillustrator** [comment]
The header is showing some weird see through pixels at the very bottom of the image, so I tried to fix that on my end. When you get a chance, you should update with this graphic.
Whistle-Webpage-Header-NoBar

**Comment by jasontheillustrator** [comment]
Also, is there any way to make the randomwalk bigger?

**Comment by KobeLiesenborgs** [comment]
We can make it bigger for sure, any thoughts on that @shiffman? Considering mobile I'm not sure how we would want the random walk sketch itself to change when viewed on mobile?

**Comment by shiffman** [comment]
thank you @KobeLiesenborgs for the work on this today! I'm going to merge this and we can discuss/make further adjustments in separate issues and branches!

**Comment by shiffman** [comment]
@allcontributors add @jasontheillustrator for design

**Comment by shiffman** [comment]
@allcontributors add @KobeLiesenborgs and @shiffman for code

**Pull request merged**
